# apps/backend/scripts/seeders/seed_ui_strings.py
# Seeds the ui_strings table with every UI string the frontend resolves via t()/pickT() — DE + EN,
# organized by namespace. tests/test_ui_strings_coverage.py keeps this list and the frontend in
# lockstep: a key used but not seeded, or seeded but unused, fails the suite.
#
# Managed seed (see _base.py): new keys are inserted; an existing row is brought in line with this
# file only while nobody has edited it in admin since it was seeded — an edited row is kept and
# logged "kept". A key removed from this list is soft-deleted in the DB only if its row is still
# unedited; a customized or admin-created row is never deleted by the seeder.

from datetime import datetime, timezone

from config.database import SessionLocal  # noqa: E402
from scripts.seeders._base import get_system_actor, human_edited_ids, is_unedited, log_action, log_kept, log_section, reconcile, seed_fingerprint
from app.Models.ui_strings import UiString
from app.Services.AuditService import AuditService


# Format: (key, namespace, value_de, value_en, description, is_locked)
UI_STRINGS: list[tuple[str, str, str, str, str | None, bool]] = [
    # ════════════════════════════════════════════════════════════════════
    # NAVIGATION (Header, mobile drawer, sticky bar)
    # ════════════════════════════════════════════════════════════════════
    ("nav.home", "nav", "Startseite", "Home", "Header nav: home link", True),
    (
        "nav.services",
        "nav",
        "Dienstleistungen",
        "Services",
        "Header nav: services link",
        True,
    ),
    ("nav.pricing", "nav", "Preise", "Pricing", "Header nav: pricing link", True),
    ("nav.about", "nav", "Über uns", "About", "Header nav: about link", True),
    ("nav.contact", "nav", "Kontakt", "Contact", "Header nav: contact link", True),
    ("nav.faq", "nav", "FAQ", "FAQ", "Footer quick link: FAQ page", False),
    (
        "nav.book_now",
        "nav",
        "Jetzt buchen",
        "Book now",
        "Header primary CTA button",
        True,
    ),
    (
        "nav.menu",
        "nav",
        "Menü öffnen",
        "Open menu",
        "Mobile drawer open label (ARIA)",
        False,
    ),
    (
        "nav.close",
        "nav",
        "Menü schließen",
        "Close menu",
        "Mobile drawer close label (ARIA)",
        False,
    ),
    # ════════════════════════════════════════════════════════════════════
    # LANGUAGE SWITCHER
    # ════════════════════════════════════════════════════════════════════
    (
        "language.switch.de",
        "language",
        "Deutsch",
        "German",
        "Language switcher: DE option label",
        True,
    ),
    (
        "language.switch.en",
        "language",
        "Englisch",
        "English",
        "Language switcher: EN option label",
        True,
    ),
    (
        "language.switch.current",
        "language",
        "Sprache wählen",
        "Choose language",
        "Language switcher: ARIA label",
        True,
    ),
    # ════════════════════════════════════════════════════════════════════
    # HOMEPAGE — HERO
    # ════════════════════════════════════════════════════════════════════
    (
        "home.hero.pre_heading",
        "hero",
        "DIE ALTERNATIVE ZUM TAXI",
        "THE ALTERNATIVE TO THE TAXI",
        "Hero eyebrow (small caps above headline)",
        False,
    ),
    (
        "home.hero.headline",
        "hero",
        "Fair, sicher, zuverlässig.",
        "Fair, safe, reliable.",
        "Hero main headline (H1)",
        False,
    ),
    (
        "home.hero.subhead",
        "hero",
        "Vorbestellte Fahrten und Kurierdienste in Deizisau, Plochingen, Esslingen und Umgebung.",
        "Pre-booked rides and courier services in Deizisau, Plochingen, Esslingen and the surrounding area.",
        "Hero subhead under H1",
        False,
    ),
    # Hero booking widget (inline quick-quote on homepage hero)
    (
        "hero_widget.heading",
        "hero",
        "Fahrt anfragen",
        "Request a ride",
        "Widget eyebrow heading",
        False,
    ),
    (
        "hero_widget.from_label",
        "hero",
        "Von",
        "From",
        "Widget pickup field label",
        False,
    ),
    (
        "hero_widget.from_placeholder",
        "hero",
        "Abholadresse",
        "Pickup address",
        "Widget pickup placeholder",
        False,
    ),
    (
        "hero_widget.to_label",
        "hero",
        "Nach",
        "To",
        "Widget destination field label",
        False,
    ),
    (
        "hero_widget.to_placeholder",
        "hero",
        "Zieladresse",
        "Destination address",
        "Widget destination placeholder",
        False,
    ),
    (
        "hero_widget.when_label",
        "hero",
        "Wann",
        "When",
        "Widget date field label",
        False,
    ),
    (
        "hero_widget.cta",
        "hero",
        "Preis anfragen",
        "Request your price",
        "Widget submit button",
        False,
    ),
    (
        "hero_widget.note",
        "hero",
        "Unverbindliche Anfrage — Antwort innerhalb von 30 Minuten. Online vorbestellen: bis zu 5 % Rabatt.",
        "Non-binding request — reply within 30 minutes. Book online: up to 5% discount.",
        "Widget caption below inputs",
        False,
    ),
    # ════════════════════════════════════════════════════════════════════
    # HOMEPAGE — TRUST STRIP (4 icons under hero)
    # ════════════════════════════════════════════════════════════════════
    (
        "home.trust.licensed",
        "trust",
        "Konzessioniert nach § 49 PBefG",
        "Licensed under § 49 PBefG",
        "Trust strip: licensing credential",
        False,
    ),
    (
        "home.trust.fixed_price",
        "trust",
        "Transparente Preise inkl. MwSt.",
        "Transparent prices incl. VAT",
        "Trust strip: pricing promise",
        False,
    ),
    (
        "home.trust.drivers",
        "trust",
        "Geprüfte, erfahrene Fahrer",
        "Vetted, experienced drivers",
        "Trust strip: driver quality",
        False,
    ),
    (
        "home.trust.always_available",
        "trust",
        "24/7 vorbestellbar",
        "Pre-book 24/7",
        "Trust strip: availability",
        False,
    ),
    (
        "home.trust.years",
        "trust",
        "Jahre Erfahrung",
        "Years of service",
        "Trust strip: years-active stat label",
        False,
    ),
    (
        "home.trust.rides",
        "trust",
        "Fahrten",
        "Rides completed",
        "Trust strip: rides-completed stat label",
        False,
    ),
    (
        "home.trust.fleet",
        "trust",
        "Fahrzeuge",
        "Vehicles",
        "Trust strip: fleet-size stat label",
        False,
    ),
    (
        "home.trust.reviews",
        "trust",
        "Bewertungen",
        "reviews",
        "Trust strip: Google review-count label",
        False,
    ),
    # ════════════════════════════════════════════════════════════════════
    # HOMEPAGE — SECTION HEADERS
    # ════════════════════════════════════════════════════════════════════
    # Services grid
    (
        "home.services.heading",
        "home",
        "Unsere Leistungen",
        "Our services",
        "Services section heading",
        False,
    ),
    (
        "home.services.subheading",
        "home",
        "Vier Leistungen — alle vorbestellt, alle zu transparenten Preisen.",
        "Four services — all pre-booked, all transparently priced.",
        "Services section lead paragraph",
        False,
    ),
    # How it works (3 steps)
    (
        "home.how.pre_heading",
        "home",
        "Ablauf",
        "How it works",
        "How-it-works eyebrow",
        False,
    ),
    (
        "home.how.heading",
        "home",
        "So einfach funktioniert Ihre Buchung",
        "How your booking works",
        "How-it-works section heading",
        False,
    ),
    (
        "home.how.step1.title",
        "home",
        "Anfrage senden",
        "Send your request",
        "Step 1 title",
        False,
    ),
    (
        "home.how.step1.body",
        "home",
        "Füllen Sie unser kurzes Buchungsformular aus oder rufen Sie uns an.",
        "Fill out our short booking form or give us a call.",
        "Step 1 body",
        False,
    ),
    (
        "home.how.step2.title",
        "home",
        "Preis bestätigen",
        "Confirm your price",
        "Step 2 title",
        False,
    ),
    (
        "home.how.step2.body",
        "home",
        "Innerhalb von 30 Minuten bestätigen wir Ihren Preis — zum Festpreis oder nach unserem transparenten Tarif.",
        "Within 30 minutes we confirm your price — a fixed price or our transparent tariff.",
        "Step 2 body",
        False,
    ),
    (
        "home.how.step3.title",
        "home",
        "Entspannt ankommen",
        "Arrive relaxed",
        "Step 3 title",
        False,
    ),
    (
        "home.how.step3.body",
        "home",
        "Ihr Fahrer wartet pünktlich am vereinbarten Ort.",
        "Your driver is waiting on time at the agreed location.",
        "Step 3 body",
        False,
    ),
    # Why StepNow
    (
        "home.why.pre_heading",
        "home",
        "Differenzierung",
        "What sets us apart",
        "Why-section eyebrow",
        False,
    ),
    (
        "home.why.heading",
        "home",
        "Warum StepNow?",
        "Why StepNow?",
        "Why-section heading",
        False,
    ),
    (
        "home.why.intro",
        "home",
        "Wir sind kein anonymes Callcenter und keine Plattform. Wir sind Ihr regionaler Partner für sichere, vorbestellte Fahrten.",
        "We're not an anonymous call centre or a platform. We're your regional partner for safe, pre-booked transfers.",
        "Why-section intro paragraph",
        False,
    ),
    (
        "home.why.bullet.fixed_price",
        "home",
        "Transparente Preise — Festpreise zum Flughafen und Hauptbahnhof, sonst ein klarer Tarif nach Kilometern.",
        "Transparent prices — fixed prices to the airport and central station, otherwise a clear distance-based tariff.",
        "Why bullet 1",
        False,
    ),
    (
        "home.why.bullet.prebooked",
        "home",
        "Vorbestellt statt Glücksspiel — Ihr Fahrer wartet bereits auf Sie.",
        "Pre-booked, not a gamble — your driver is already waiting for you.",
        "Why bullet 2",
        False,
    ),
    (
        "home.why.bullet.licensed",
        "home",
        "Konzessioniert und versichert — volle Personenbeförderungs-Haftpflicht.",
        "Licensed and insured — full passenger-transport liability cover.",
        "Why bullet 3",
        False,
    ),
    (
        "home.why.bullet.personal",
        "home",
        "Persönlicher Service — direkter Kontakt, kein anonymes Callcenter.",
        "Personal service — direct contact, no anonymous call centre.",
        "Why bullet 4",
        False,
    ),
    # Fleet preview
    (
        "home.fleet.pre_heading",
        "home",
        "Die Flotte",
        "The fleet",
        "Fleet section eyebrow",
        False,
    ),
    (
        "home.fleet.heading_count",
        "home",
        "Drei Fahrzeuge,",
        "Three vehicles,",
        "Fleet heading part 1 (count + comma) — overridden dynamically when vehicle count differs",
        False,
    ),
    (
        "home.fleet.heading_standard",
        "home",
        "ein Standard.",
        "one standard.",
        "Fleet heading part 2 (italic gold accent)",
        False,
    ),
    (
        "home.fleet.lead",
        "home",
        "Eine kleine, bewusst gewählte Flotte. Jedes Fahrzeug wird einzeln betreut — keine geteilten Schlüssel, keine anonyme Übergabe zwischen Schichten.",
        "A small, deliberate fleet. Each vehicle is maintained on a single-driver basis — no shared keys, no anonymous handover between shifts.",
        "Fleet section lead paragraph",
        False,
    ),
    # Testimonials
    (
        "home.testimonials.pre_heading",
        "home",
        "Kundenstimmen",
        "Customer voices",
        "Testimonials section eyebrow",
        False,
    ),
    (
        "home.testimonials.heading",
        "home",
        "Was unsere Kunden sagen",
        "What our customers say",
        "Testimonials section heading",
        False,
    ),
    # FAQ (homepage teaser — SINGULAR "faq")
    (
        "home.faq.pre_heading",
        "home",
        "FAQ",
        "FAQ",
        "FAQ section eyebrow (small caps)",
        False,
    ),
    (
        "home.faq.heading",
        "home",
        "Häufige Fragen",
        "Frequently asked questions",
        "FAQ section heading (homepage)",
        False,
    ),
    (
        "home.faq.view_all",
        "home",
        "Alle Fragen ansehen",
        "View all questions",
        "Link to full FAQ",
        False,
    ),
    # FAQ (contact page — PLURAL "faqs", separate key)
    (
        "home.faqs.heading",
        "home",
        "Antworten auf einen Blick",
        "Answers at a glance",
        "FAQ heading on contact page (plural-form key used by /kontakt and /en/contact)",
        False,
    ),
    # ════════════════════════════════════════════════════════════════════
    # SERVICES — LIST PAGE (magazine spread)
    # ════════════════════════════════════════════════════════════════════
    (
        "services.page.title",
        "services",
        "Unsere Leistungen",
        "Our services",
        "Services list page H1 / metadata",
        False,
    ),
    (
        "services.page.subhead",
        "services",
        "Vier Leistungen für Privat- und Geschäftskunden in Deizisau, Plochingen, Esslingen und Umgebung.",
        "Four services for private and business customers in Deizisau, Plochingen, Esslingen and the surrounding area.",
        "Services list page subhead",
        False,
    ),
    (
        "services.page.eyebrow",
        "services",
        "Leistungen",
        "Services",
        "Services list page eyebrow above H1",
        False,
    ),
    (
        "services.page.heading_part1",
        "services",
        "Vier Wege",
        "Four ways",
        "Services page H1 part 1 (large display)",
        False,
    ),
    (
        "services.page.heading_part2",
        "services",
        "ans Ziel.",
        "to get there.",
        "Services page H1 part 2 (italic gold accent)",
        False,
    ),
    (
        "services.page.region",
        "services",
        "Stuttgart · Esslingen · Deizisau",
        "Stuttgart · Esslingen · Deizisau",
        "Region label on services page",
        False,
    ),
    # Services index strip (sticky overview row)
    (
        "services.price.from",
        "services",
        "Ab",
        "From",
        "Price prefix on a service card (capitalised, stands alone)",
        False,
    ),
    (
        "services.price.from_inline",
        "services",
        "ab",
        "from",
        "Price prefix after a route label, mid-sentence",
        False,
    ),
    (
        "services.price.on_request",
        "services",
        "Auf Anfrage",
        "On request",
        "Shown instead of a price when a service has no published routes",
        False,
    ),
    (
        "services.index.read_more",
        "services",
        "Mehr lesen",
        "Read more",
        "Link on a service card in the At-a-glance strip",
        False,
    ),
    (
        "services.snapshot.all_prices",
        "services",
        "Alle Preise",
        "View full pricing",
        "Link from a service's price snapshot to the pricing page",
        False,
    ),
    (
        "services.index.eyebrow",
        "services",
        "Im Überblick",
        "At a glance",
        "Services-index strip eyebrow",
        False,
    ),
    # Service card
    (
        "services.card.learn_more",
        "services",
        "Mehr erfahren",
        "Learn more",
        "Service card CTA",
        False,
    ),
    # Service detail page
    (
        "services.detail.cta_book",
        "services",
        "Diesen Service jetzt buchen",
        "Book this service now",
        "Service detail page primary CTA",
        False,
    ),
    # Related services (cross-sell)
    (
        "services.related.eyebrow",
        "services",
        "Weitere Leistungen",
        "More services",
        "Related-services eyebrow",
        False,
    ),
    (
        "services.related.heading",
        "services",
        "Das könnte Sie auch interessieren",
        "You might also be interested in",
        "Related-services heading",
        False,
    ),
    # Short service labels (used by Footer + page headings)
    (
        "services.flughafentransfer",
        "services",
        "Flughafen-Transfer",
        "Airport transfer",
        "Short label — Footer, hero feature block",
        True,
    ),
    (
        "services.krankenhausfahrten",
        "services",
        "Arzt- & Klinikfahrten",
        "Doctor & clinic rides",
        "Short label — Footer, hero feature block",
        True,
    ),
    (
        "services.shuttle",
        "services",
        "Shuttle Service",
        "Shuttle service",
        "Short label — Footer, hero feature block",
        True,
    ),
    (
        "services.courier",
        "services",
        "Express-Kurier & Terminfracht",
        "Express courier & freight",
        "Short label — Footer, hero feature block",
        True,
    ),
    # Per-service differentiator blocks on the services magazine page
    (
        "services.row.flughafentransfer.diff_label",
        "services",
        "Festpreis ab Wohnort",
        "Fixed price from your town",
        "Airport transfer — differentiator label (DE slug)",
        False,
    ),
    (
        "services.row.flughafentransfer.diff_body",
        "services",
        "— pro Fahrzeug bis zu 4 Personen, zum Flughafen oder Hauptbahnhof Stuttgart.",
        "— per vehicle for up to 4 persons, to Stuttgart Airport or Central Station.",
        "Airport transfer — differentiator body (DE slug)",
        False,
    ),
    (
        "services.row.airport-transfer.diff_label",
        "services",
        "Festpreis ab Wohnort",
        "Fixed price from your town",
        "Airport transfer — differentiator label (EN slug)",
        False,
    ),
    (
        "services.row.airport-transfer.diff_body",
        "services",
        "— pro Fahrzeug bis zu 4 Personen, zum Flughafen oder Hauptbahnhof Stuttgart.",
        "— per vehicle for up to 4 persons, to Stuttgart Airport or Central Station.",
        "Airport transfer — differentiator body (EN slug)",
        False,
    ),
    (
        "services.row.krankenhausfahrten.diff_label",
        "services",
        "Geschult in Begleitung",
        "Trained for assistance",
        "Hospital transport — differentiator label (DE slug)",
        False,
    ),
    (
        "services.row.krankenhausfahrten.diff_body",
        "services",
        "— Tür-zu-Tür-Abholung, Hilfe mit Gepäck und Gehhilfen, optionale Wartezeit bei kurzen Terminen.",
        "— door-to-door pickup, support with bags and walking aids, optional wait time during short appointments.",
        "Hospital transport — differentiator body (DE slug)",
        False,
    ),
    (
        "services.row.hospital-transport.diff_label",
        "services",
        "Geschult in Begleitung",
        "Trained for assistance",
        "Hospital transport — differentiator label (EN slug)",
        False,
    ),
    (
        "services.row.hospital-transport.diff_body",
        "services",
        "— Tür-zu-Tür-Abholung, Hilfe mit Gepäck und Gehhilfen, optionale Wartezeit bei kurzen Terminen.",
        "— door-to-door pickup, support with bags and walking aids, optional wait time during short appointments.",
        "Hospital transport — differentiator body (EN slug)",
        False,
    ),
    (
        "services.row.shuttle-service.diff_label",
        "services",
        "Bis zu 4 Personen",
        "Up to 4 persons",
        "Shuttle service — differentiator label",
        False,
    ),
    (
        "services.row.shuttle-service.diff_body",
        "services",
        "pro Fahrzeug — für größere Gruppen setzen wir mehrere Fahrzeuge ein und koordinieren die gesamte Fahrt.",
        "per vehicle — for larger groups we deploy several vehicles and coordinate the whole journey.",
        "Shuttle service — differentiator body",
        False,
    ),
    # How-it-works beat (dark band on services page)
    (
        "services.hiw.eyebrow",
        "services",
        "So funktioniert's",
        "How it works",
        "Services HIW eyebrow",
        False,
    ),
    (
        "services.hiw.heading_part1",
        "services",
        "Drei Schritte,",
        "Three steps,",
        "Services HIW heading part 1",
        False,
    ),
    (
        "services.hiw.heading_part2",
        "services",
        "keine Überraschungen.",
        "no surprises.",
        "Services HIW heading part 2 (italic gold)",
        False,
    ),
    (
        "services.hiw.step1.heading",
        "services",
        "Route und Datum senden",
        "Send your route and date",
        "HIW step 1 heading",
        False,
    ),
    (
        "services.hiw.step1.body",
        "services",
        "Per Webformular, Telefon oder WhatsApp. Geben Sie Zeit, Abholort und Ziel an — wir kümmern uns um den Rest.",
        "By web form, phone or WhatsApp. Include the time, the pickup point and the destination — we'll handle the rest.",
        "HIW step 1 body",
        False,
    ),
    (
        "services.hiw.step2.heading",
        "services",
        "Ihr Preis innerhalb von 30 Min.",
        "Your price within 30 min",
        "HIW step 2 heading",
        False,
    ),
    (
        "services.hiw.step2.body",
        "services",
        "Während der Telefonzeiten bestätigen wir Preis, Fahrer und Fahrzeug — zum Festpreis oder nach unserem Tarif.",
        "During phone hours we confirm the price, the driver and the vehicle — a fixed price or our tariff.",
        "HIW step 2 body",
        False,
    ),
    (
        "services.hiw.step3.heading",
        "services",
        "Der Fahrer ist schon da",
        "The driver is already there",
        "HIW step 3 heading",
        False,
    ),
    (
        "services.hiw.step3.body",
        "services",
        "Kein Heranwinken, keine App-Vermittlung, keine Aufschläge zu Stoßzeiten. Ein bestätigter Festpreis bleibt fest — auch im Stau.",
        "No hailing, no app dispatch, no peak-time surcharges. A confirmed fixed price stays fixed — even in traffic.",
        "HIW step 3 body",
        False,
    ),
    # Editorial close (bottom of services page)
    (
        "services.close.eyebrow",
        "services",
        "Vier Services, ein Standard",
        "Four services, one standard",
        "Services editorial close eyebrow",
        False,
    ),
    (
        "services.close.statement_part1",
        "services",
        "Jede Fahrt beginnt mit einem ",
        "Every ride starts with a ",
        "Editorial close statement part 1 (note trailing space)",
        False,
    ),
    (
        "services.close.statement_accent",
        "services",
        "Preis, den Sie sehen",
        "price you can see",
        "Editorial close statement accent (gold)",
        False,
    ),
    (
        "services.close.statement_part2",
        "services",
        ", einem Fahrer, den Sie namentlich kennen, und einer Route, die vor der Abfahrt bestätigt ist.",
        ", a driver you can name, and a route confirmed before you leave home.",
        "Editorial close statement part 2",
        False,
    ),
    (
        "services.close.attribution",
        "services",
        "KONZESSIONIERTER PERSONENVERKEHR · PLOCHINGEN/ESSLINGEN",
        "LICENSED PASSENGER TRANSPORT · PLOCHINGEN/ESSLINGEN",
        "Editorial close attribution line",
        False,
    ),
    (
        "services.close.followup_lead",
        "services",
        "Alle Preise im Überblick?",
        "Looking for our prices?",
        "Editorial close follow-up lead text",
        False,
    ),
    (
        "services.close.followup_link",
        "services",
        "Vollständige Preise →",
        "See full pricing →",
        "Editorial close follow-up link label",
        False,
    ),
    # ════════════════════════════════════════════════════════════════════
    # PRICING PAGE
    # ════════════════════════════════════════════════════════════════════
    (
        "pricing.page.eyebrow",
        "pricing",
        "Preise",
        "Pricing",
        "Pricing page eyebrow",
        False,
    ),
    (
        "pricing.page.title",
        "pricing",
        "Unsere Preise",
        "Our prices",
        "Pricing page H1",
        False,
    ),
    (
        "pricing.page.intro",
        "pricing",
        "Festpreise zum Flughafen und Hauptbahnhof Stuttgart, feste Preise für Stadtfahrten und ein klarer Kilometertarif — transparent, direkt, pünktlich.",
        "Fixed prices to Stuttgart Airport and Central Station, fixed prices for local rides and a clear per-kilometre tariff — transparent, direct, punctual.",
        "Pricing page intro paragraph",
        False,
    ),
    (
        "pricing.disclaimer",
        "pricing",
        "Personenfahrten: Endpreise inkl. gesetzlicher MwSt., pro Fahrzeug für bis zu 4 Personen. Kurierpreise netto zzgl. MwSt. Personenbeförderung nach § 49 PBefG.",
        "Passenger rides: final prices incl. statutory VAT, per vehicle for up to 4 persons. Courier prices net plus VAT. Passenger transport under § 49 PBefG.",
        "Pricing page sub-intro (also used by PricingSnapshot)",
        False,
    ),
    (
        "pricing.footnote",
        "pricing",
        "Festpreise gelten je einfacher Fahrt — Hin- und Rückfahrt sind zwei Fahrten. Alle Preise gelten für bis zu 4 Personen (Fahrzeugkapazität). Andere Strecken auf Anfrage.",
        "Fixed prices apply per one-way trip — outbound and return are two trips. All prices apply to up to 4 persons (vehicle capacity). Other routes on request.",
        "Footnote below per-service pricing table",
        False,
    ),
    # Pricing table column headers
    (
        "pricing.table.price",
        "pricing",
        "Preis",
        "Price",
        "Pricing table column",
        False,
    ),
    (
        "pricing.empty.heading",
        "pricing",
        "Preis auf Anfrage",
        "Price on request",
        "Empty pricing state heading",
        False,
    ),
    (
        "pricing.empty.cta",
        "pricing",
        "Angebot anfordern",
        "Request a quote",
        "Empty pricing state CTA",
        False,
    ),
    # Tabbed price list
    (
        "pricing.tabs.eyebrow",
        "pricing",
        "Aktuelle Preisliste",
        "Current price list",
        "Tabbed price list eyebrow",
        False,
    ),
    (
        "pricing.tabs.heading",
        "pricing",
        "Jede Strecke, jeder Service",
        "Every route, every service",
        "Tabbed price list heading",
        False,
    ),
    (
        "pricing.tabs.lead",
        "pricing",
        "Alle Preise aus unserer aktuellen Preisliste. Für andere Strecken erhalten Sie ein Angebot innerhalb von 30 Minuten.",
        "All prices from our current price list. For other routes you receive a quote within 30 minutes.",
        "Tabbed price list lead paragraph",
        False,
    ),
    (
        "pricing.tabs.aria_label",
        "pricing",
        "Preise nach Service",
        "Pricing by service",
        "Tab list ARIA label",
        False,
    ),
    # Trust strip (italic serif blockquote between tables and moment)
    (
        "pricing.trust.before",
        "pricing",
        "Transparente Preise vor Fahrtbeginn. ",
        "Transparent prices before departure. ",
        "Trust strip text before accent",
        False,
    ),
    (
        "pricing.trust.accent",
        "pricing",
        "Keine versteckten Aufschläge,",
        "No hidden surcharges,",
        "Trust strip gold-accented phrase",
        False,
    ),
    (
        "pricing.trust.after",
        "pricing",
        " kein Überraschungspreis am Zielort.",
        " no surprise total at the destination.",
        "Trust strip text after accent",
        False,
    ),
    (
        "pricing.trust.attribution",
        "pricing",
        "— FAIR · SICHER · ZUVERLÄSSIG",
        "— FAIR · SAFE · RELIABLE",
        "Trust strip attribution caption",
        False,
    ),
    # included moment
    (
        "pricing.included.big_caption",
        "pricing",
        "MWST. INKLUSIVE",
        "VAT INCLUDED",
        " display caption",
        False,
    ),
    (
        "pricing.included.eyebrow",
        "pricing",
        "Was Ihr Fahrpreis abdeckt",
        "What your fare covers",
        "Included-moment eyebrow",
        False,
    ),
    (
        "pricing.included.heading",
        "pricing",
        "Klare Preise, keine versteckten Kosten.",
        "Clear prices, no hidden costs.",
        "Included-moment heading",
        False,
    ),
    (
        "pricing.included.lead",
        "pricing",
        "Alle Preise für Personenfahrten sind Endpreise inkl. gesetzlicher MwSt. und gelten pro Fahrzeug — für bis zu 4 Personen.",
        "All passenger prices are final prices incl. statutory VAT and apply per vehicle — for up to 4 persons.",
        "Included-moment lead paragraph",
        False,
    ),
    (
        "pricing.included.luggage.label",
        "pricing",
        "Standardgepäck",
        "Standard luggage",
        "Included row: luggage label",
        False,
    ),
    (
        "pricing.included.luggage.desc",
        "pricing",
        "— 1 Koffer + 1 Handgepäck pro Person.",
        "— 1 case + 1 cabin bag per person.",
        "Included row: luggage description",
        False,
    ),
    (
        "pricing.included.childseat.label",
        "pricing",
        "Kindersitz oder Sitzerhöhung",
        "Child seat or booster",
        "Included row: child seat label",
        False,
    ),
    (
        "pricing.included.childseat.desc",
        "pricing",
        "— auf Anfrage.",
        "— on request.",
        "Included row: child seat description",
        False,
    ),
    (
        "pricing.included.flighttrack.label",
        "pricing",
        "Flugverfolgung",
        "Flight tracking",
        "Included row: flight tracking label",
        False,
    ),
    (
        "pricing.included.flighttrack.desc",
        "pricing",
        "— wir passen die Abholzeit bei Verspätungen an.",
        "— we adjust pickup if your flight is delayed.",
        "Included row: flight tracking description",
        False,
    ),
    # Excluded strip (single horizontal "Charged separately" row)
    (
        "pricing.excluded.label",
        "pricing",
        "Separat berechnet",
        "Charged separately",
        "Excluded-items strip label",
        False,
    ),
    (
        "pricing.excluded.tolls",
        "pricing",
        "Mautgebühren",
        "Toll charges",
        "Excluded item",
        False,
    ),
    (
        "pricing.excluded.parking",
        "pricing",
        "Parkgebühren am Zielort",
        "Parking fees at destination",
        "Excluded item",
        False,
    ),
    (
        "pricing.excluded.cleaning",
        "pricing",
        "Reinigungszuschlag bei Verschmutzung",
        "Cleaning surcharge if soiled",
        "Excluded item: cleaning surcharge",
        False,
    ),
    # Comparison table (StepNow vs standard taxi)
    (
        "pricing.comparison.eyebrow",
        "pricing",
        "Gleiche Fahrt — anderes Erlebnis",
        "Same ride — different experience",
        "Comparison eyebrow",
        False,
    ),
    (
        "pricing.comparison.heading",
        "pricing",
        "StepNow vs. ein normales Taxi",
        "StepNow vs. a standard taxi",
        "Comparison heading",
        False,
    ),
    (
        "pricing.comparison.lead",
        "pricing",
        "Der Unterschied liegt in dem, was Sie vor der Fahrt wissen.",
        "The difference is in what you know before the ride starts.",
        "Comparison lead paragraph",
        False,
    ),
    (
        "pricing.comparison.head_label",
        "pricing",
        "Erlebnis",
        "Experience",
        "Comparison column header (left)",
        False,
    ),
    (
        "pricing.comparison.head_taxi",
        "pricing",
        "Normales Taxi",
        "Standard taxi",
        "Comparison column header (right)",
        False,
    ),
    (
        "pricing.comparison.row1.label",
        "pricing",
        "Preis Flughafen-Transfer",
        "Airport transfer price",
        "Comparison row 1 label",
        False,
    ),
    (
        "pricing.comparison.row1.stepnow",
        "pricing",
        "Festpreis ab {price} — pro Fahrzeug, inkl. MwSt.",
        "Fixed price from {price} — per vehicle, VAT included",
        "Comparison row 1 StepNow",
        False,
    ),
    (
        "pricing.comparison.row1.taxi",
        "pricing",
        "Taxameter — vom Verkehr abhängig, Endpreis erst bei Ankunft",
        "Meter-based — depends on traffic, final price only on arrival",
        "Comparison row 1 taxi",
        False,
    ),
    (
        "pricing.comparison.row2.label",
        "pricing",
        "Zugewiesener Fahrer",
        "Driver assigned",
        "Comparison row 2 label",
        False,
    ),
    (
        "pricing.comparison.row2.stepnow",
        "pricing",
        "Gleiche Nummer, gleicher Fahrer, jedes Mal",
        "Same number, same driver, every time",
        "Comparison row 2 StepNow",
        False,
    ),
    (
        "pricing.comparison.row2.taxi",
        "pricing",
        "Wen auch immer die Zentrale schickt",
        "Whoever dispatch sends",
        "Comparison row 2 taxi",
        False,
    ),
    (
        "pricing.comparison.row3.label",
        "pricing",
        "Im Voraus gebucht",
        "Booked in advance",
        "Comparison row 3 label",
        False,
    ),
    (
        "pricing.comparison.row3.stepnow",
        "pricing",
        "Online oder telefonisch vorbestellt",
        "Pre-booked online or by phone",
        "Comparison row 3 StepNow",
        False,
    ),
    (
        "pricing.comparison.row3.taxi",
        "pricing",
        "Am Tag selbst herangerufen, Verfügbarkeit unklar",
        "Hailed on the day, hope for availability",
        "Comparison row 3 taxi",
        False,
    ),
    (
        "pricing.comparison.row4.label",
        "pricing",
        "Meet & Greet am Flughafen",
        "Meet & greet at airport",
        "Comparison row 4 label",
        False,
    ),
    (
        "pricing.comparison.row4.stepnow",
        "pricing",
        "Bei Flughafenstrecken inklusive",
        "Included with airport routes",
        "Comparison row 4 StepNow",
        False,
    ),
    (
        "pricing.comparison.row4.taxi",
        "pricing",
        "Zusatzservice falls verfügbar",
        "Extra service if available",
        "Comparison row 4 taxi",
        False,
    ),
    (
        "pricing.comparison.row5.label",
        "pricing",
        "Rechnung für Geschäftskunden",
        "Receipt for business",
        "Comparison row 5 label",
        False,
    ),
    (
        "pricing.comparison.row5.stepnow",
        "pricing",
        "Detaillierte Rechnung nach Vereinbarung",
        "Detailed invoice, by arrangement",
        "Comparison row 5 StepNow",
        False,
    ),
    (
        "pricing.comparison.row5.taxi",
        "pricing",
        "Handgeschriebene oder gedruckte Quittung",
        "Handwritten or printed slip",
        "Comparison row 5 taxi",
        False,
    ),
    # Payment methods
    (
        "pricing.payment.eyebrow",
        "pricing",
        "Bezahlung",
        "Payment",
        "Payment row eyebrow",
        False,
    ),
    (
        "pricing.payment.heading",
        "pricing",
        "So zahlen Sie",
        "How to pay",
        "Payment row heading",
        False,
    ),
    ("pricing.payment.cash", "pricing", "Bar", "Cash", "Payment method: cash", False),
    (
        "pricing.payment.girocard",
        "pricing",
        "Girocard / EC",
        "Girocard / debit card",
        "Payment method: girocard",
        False,
    ),
    (
        "pricing.payment.invoice",
        "pricing",
        "Rechnung (B2B)",
        "Invoice (B2B)",
        "Payment method: invoice",
        False,
    ),
    (
        "pricing.payment.paypal",
        "pricing",
        "PayPal",
        "PayPal",
        "Payment method: PayPal",
        False,
    ),
    # Cancellation policy
    (
        "pricing.cancellation.eyebrow",
        "pricing",
        "Stornierung",
        "Cancellation",
        "Cancellation row eyebrow",
        False,
    ),
    (
        "pricing.cancellation.heading",
        "pricing",
        "Faire Bedingungen",
        "Fair terms",
        "Cancellation row heading",
        False,
    ),
    (
        "pricing.cancellation.full_terms",
        "pricing",
        "Vollständige AGB ansehen →",
        "See full terms (AGB) →",
        "Cancellation full-terms link",
        False,
    ),
    # ════════════════════════════════════════════════════════════════════
    # ABOUT PAGE
    # ════════════════════════════════════════════════════════════════════
    (
        "about.page.title",
        "about",
        "Über StepNow",
        "About StepNow",
        "About page H1 / metadata",
        False,
    ),
    (
        "about.page.subhead",
        "about",
        "Wir sind Ihr professioneller Fahrdienst als Alternative zum Taxi und bieten sichere, komfortable sowie zuverlässige Fahrten für Privat- und Geschäftskunden. Mit einem gepflegten Fuhrpark, erfahrenen Fahrern und konsequent kundenorientiertem Service stehen wir für Qualität und Pünktlichkeit. Ob Flughafen-Transfer, Arzt- und Klinikfahrt, Shuttle oder Express-Kurier — wir bringen Sie und Ihre Sendungen entspannt und sicher ans Ziel.",
        "We are your professional driver service as an alternative to the taxi, offering safe, comfortable and reliable trips for private and business customers. With a well-maintained fleet, experienced drivers and consistently customer-focused service, we stand for quality and punctuality. Whether airport transfer, doctor or clinic ride, shuttle or express courier — we get you and your shipments to their destination relaxed and safe.",
        "About page subhead",
        False,
    ),
    (
        "about.page.eyebrow",
        "about",
        "Über uns",
        "About",
        "About page eyebrow above H1",
        False,
    ),
    # Story section
    (
        "about.story.eyebrow",
        "about",
        "Die Geschichte",
        "The story",
        "Story section eyebrow",
        False,
    ),
    (
        "about.story.heading",
        "about",
        "Meine Geschichte",
        "My story",
        "Story section heading",
        False,
    ),
    (
        "about.story.author",
        "about",
        "Naeem Ahmad",
        "Naeem Ahmad",
        "Owner name displayed under the portrait",
        False,
    ),
    (
        "about.story.role",
        "about",
        "Inhaber",
        "Owner",
        "Role label shown next to the owner name in the story section",
        False,
    ),
    (
        "about.story.placeholder",
        "about",
        "Unsere Geschichte wird in Kürze erzählt.",
        "Our story will be told shortly.",
        "Story section placeholder when no paragraphs are seeded",
        False,
    ),
    (
        "about.story.paragraph_1",
        "about",
        "Ich bin Naeem Ahmad — Inhaber von StepNow Rides & Movers und seit über zehn Jahren in Plochingen/Esslingen unterwegs.",
        "I'm Naeem Ahmad — owner of StepNow Rides & Movers and a driver in Plochingen/Esslingen for more than ten years.",
        "Story paragraph 1",
        False,
    ),
    (
        "about.story.paragraph_2",
        "about",
        "StepNow ist aus einer einfachen Idee entstanden: Mobilität soll vorhersehbar sein. Faire, transparente Preise, keine Überraschungen am Taxameter und ein Fahrer, der pünktlich am vereinbarten Ort wartet.",
        "StepNow grew from a simple idea: mobility should be predictable. Fair, transparent prices, no taximeter surprises, and a driver who is on time at the agreed location.",
        "Story paragraph 2",
        False,
    ),
    (
        "about.story.paragraph_3",
        "about",
        "Wir sind kein anonymes Callcenter. Wenn Sie bei uns buchen, sprechen Sie direkt mit dem Inhaber — und unser Team kennt die Strecken zwischen Esslingen, Stuttgart und Umgebung wie die eigene Westentasche.",
        "We are not an anonymous call centre. When you book with us, you speak directly with the owner — and our team knows the routes between Esslingen, Stuttgart and the surrounding area like the back of their hand.",
        "Story paragraph 3",
        False,
    ),
    (
        "about.story.paragraph_4",
        "about",
        "Ob Flughafen-Transfer, Arzt- und Klinikfahrt, Shuttle oder Express-Kurier — wir behandeln jede Fahrt mit dem Respekt, den sie verdient.",
        "Whether it's an airport transfer, a doctor or clinic ride, a shuttle or an express courier run — we treat every trip with the respect it deserves.",
        "Story paragraph 4",
        False,
    ),
    (
        "about.story.servicegebiet",
        "about",
        "Unser Servicegebiet: Deizisau · Plochingen · Wernau · Denkendorf · Köngen · Esslingen · Kirchheim (Teck) und Umgebung.",
        "Our service area: Deizisau · Plochingen · Wernau · Denkendorf · Köngen · Esslingen · Kirchheim (Teck) and the surrounding region.",
        "Service area line shown in the About story section",
        False,
    ),
    # Values section
    (
        "about.values.eyebrow",
        "about",
        "Unsere Prinzipien",
        "Our principles",
        "Values eyebrow",
        False,
    ),
    (
        "about.values.heading",
        "about",
        "Was uns trägt",
        "What we stand for",
        "Values heading",
        False,
    ),
    (
        "about.values.reliability.title",
        "about",
        "Verlässlichkeit",
        "Reliability",
        "Value title 1",
        False,
    ),
    (
        "about.values.reliability.body",
        "about",
        "Pünktlich, vorbestellt, bestätigt — keine Überraschungen am Abholtag.",
        "On time, pre-booked, confirmed — no surprises on pickup day.",
        "Value body 1",
        False,
    ),
    (
        "about.values.safety.title",
        "about",
        "Sicherheit",
        "Safety",
        "Value title 2",
        False,
    ),
    (
        "about.values.safety.body",
        "about",
        "Geprüfte Fahrer, gewartete Fahrzeuge und volle Haftpflicht.",
        "Vetted drivers, maintained vehicles and full liability insurance.",
        "Value body 2",
        False,
    ),
    (
        "about.values.transparency.title",
        "about",
        "Transparenz",
        "Transparency",
        "Value title 3",
        False,
    ),
    (
        "about.values.transparency.body",
        "about",
        "Festpreise und ein klarer Tarif — alle Personenfahrten inkl. MwSt., keine versteckten Aufschläge.",
        "Fixed prices and a clear tariff — all passenger rides incl. VAT, no hidden surcharges.",
        "Value body 3",
        False,
    ),
    (
        "about.values.service.title",
        "about",
        "Persönlicher Service",
        "Personal service",
        "Value title 4",
        False,
    ),
    (
        "about.values.service.body",
        "about",
        "Direkter Kontakt zum Inhaber, kein anonymes Callcenter.",
        "Direct contact with the owner — no anonymous call centre.",
        "Value body 4",
        False,
    ),
    # Credentials section
    (
        "about.credentials.eyebrow",
        "about",
        "Qualifikationen",
        "Credentials",
        "Credentials eyebrow",
        False,
    ),
    (
        "about.credentials.heading",
        "about",
        "Qualifikationen & Zulassungen",
        "Credentials & licences",
        "Credentials heading",
        False,
    ),
    (
        "about.credentials.pbefg.title",
        "about",
        "Konzession nach § 49 PBefG",
        "Licence under § 49 PBefG",
        "Credential 1 title",
        False,
    ),
    (
        "about.credentials.pbefg.body",
        "about",
        "Lizenziert nach dem deutschen Personenbeförderungsgesetz. Volle Konzessionspflicht erfüllt.",
        "Licensed under the German Passenger Transport Act. Full concession compliance.",
        "Credential 1 body",
        False,
    ),
    (
        "about.credentials.bkrfqg.title",
        "about",
        "Berufskraftfahrer-Qualifikation",
        "Professional driver qualification",
        "Credential 2 title",
        False,
    ),
    (
        "about.credentials.bkrfqg.body",
        "about",
        "Qualifikation nach BKrFQG mit regelmäßigen Weiterbildungen.",
        "BKrFQG-certified with regular continuing education.",
        "Credential 2 body",
        False,
    ),
    (
        "about.credentials.insurance.title",
        "about",
        "Personenbeförderungs-Haftpflicht",
        "Passenger-transport liability",
        "Credential 3 title",
        False,
    ),
    (
        "about.credentials.insurance.body",
        "about",
        "Volle Personenbeförderungs-Haftpflichtversicherung für alle Fahrten.",
        "Full passenger-transport liability insurance on every ride.",
        "Credential 3 body",
        False,
    ),
    (
        "about.credentials.handelsregister.title",
        "about",
        "Eintrag im Handelsregister",
        "Trade register entry",
        "Credential 4 title",
        False,
    ),
    (
        "about.credentials.handelsregister.body",
        "about",
        "Eingetragenes Unternehmen am Amtsgericht — Geschäftssitz Deizisau.",
        "Registered business at the local commercial court — based in Deizisau.",
        "Credential 4 body",
        False,
    ),
    # Service-area section
    (
        "about.area.eyebrow",
        "about",
        "Einsatzgebiet",
        "Service area",
        "Service-area eyebrow",
        False,
    ),
    (
        "about.area.heading",
        "about",
        "Wo wir fahren",
        "Where we operate",
        "Service-area heading",
        False,
    ),
    (
        "about.area.body",
        "about",
        "Wir fahren in Plochingen, Esslingen, Deizisau und im mittleren Neckartal — sowie zu allen umliegenden Flughäfen.",
        "We operate in Plochingen, Esslingen, Deizisau and the central Neckar valley — plus rides to all surrounding airports.",
        "Service-area body paragraph",
        False,
    ),
    (
        "about.area.open_external",
        "about",
        "In Karten öffnen",
        "Open in maps",
        "Service-area external-map button",
        False,
    ),
    (
        "about.area.empty.title",
        "about",
        "Karte nicht verfügbar",
        "Map not available",
        "Service-area empty-state title",
        False,
    ),
    (
        "about.area.empty.body",
        "about",
        "Standort wird in Kürze hinterlegt.",
        "Location will be added shortly.",
        "Service-area empty-state body",
        False,
    ),
    # ════════════════════════════════════════════════════════════════════
    # CONTACT PAGE
    # ════════════════════════════════════════════════════════════════════
    (
        "contact.page.title",
        "contact",
        "Kontakt",
        "Contact",
        "Contact page H1 / metadata",
        False,
    ),
    (
        "contact.page.subhead",
        "contact",
        "So erreichen Sie uns Telefon, E-Mail oder direkt vor Ort.",
        "How to reach us phone, email or in person.",
        "Contact page subhead",
        False,
    ),
    (
        "contact.page.eyebrow",
        "contact",
        "Kontakt",
        "Contact",
        "Contact page eyebrow above H1",
        False,
    ),
    # Methods (sidebar column)
    (
        "contact.methods.eyebrow",
        "contact",
        "Direkt",
        "Direct",
        "Methods column eyebrow",
        False,
    ),
    (
        "contact.methods.heading",
        "contact",
        "So erreichen Sie uns",
        "How to reach us",
        "Methods column heading",
        False,
    ),
    (
        "contact.method.phone",
        "contact",
        "Telefon",
        "Phone",
        "Method label: phone",
        False,
    ),
    (
        "contact.method.email",
        "contact",
        "E-Mail",
        "Email",
        "Method label: email",
        False,
    ),
    (
        "contact.method.address",
        "contact",
        "Adresse",
        "Address",
        "Method label: address",
        False,
    ),
    (
        "contact.method.whatsapp",
        "contact",
        "WhatsApp",
        "WhatsApp",
        "Method label: WhatsApp",
        False,
    ),
    # Form (main column)
    (
        "contact.form.eyebrow",
        "contact",
        "Anfrage",
        "Inquiry",
        "Form column eyebrow",
        False,
    ),
    (
        "contact.form.heading",
        "contact",
        "Schreiben Sie uns",
        "Write to us",
        "Form column heading",
        False,
    ),
    ("contact.form.name", "contact", "Name", "Name", "Form field: name", False),
    ("contact.form.email", "contact", "E-Mail", "Email", "Form field: email", False),
    (
        "contact.form.phone",
        "contact",
        "Telefon (optional)",
        "Phone (optional)",
        "Form field: phone",
        False,
    ),
    (
        "contact.form.subject",
        "contact",
        "Betreff",
        "Subject",
        "Form field: subject",
        False,
    ),
    (
        "contact.form.subject.general",
        "contact",
        "Allgemeine Anfrage",
        "General inquiry",
        "Subject option",
        False,
    ),
    (
        "contact.form.subject.booking",
        "contact",
        "Buchung",
        "Booking",
        "Subject option",
        False,
    ),
    (
        "contact.form.subject.complaint",
        "contact",
        "Beschwerde",
        "Complaint",
        "Subject option",
        False,
    ),
    (
        "contact.form.subject.business",
        "contact",
        "Geschäftskunde",
        "Business customer",
        "Subject option",
        False,
    ),
    (
        "contact.form.subject.other",
        "contact",
        "Sonstiges",
        "Other",
        "Subject option",
        False,
    ),
    (
        "contact.form.message",
        "contact",
        "Nachricht",
        "Message",
        "Form field: message",
        False,
    ),
    (
        "contact.form.submit",
        "contact",
        "Nachricht senden",
        "Send message",
        "Form submit button",
        False,
    ),
    (
        "contact.form.success.body",
        "contact",
        "Wir melden uns innerhalb eines Werktages bei Ihnen.",
        "We'll get back to you within one business day.",
        "Form success body",
        False,
    ),
    (
        "contact.form.consent_intro",
        "contact",
        "Ich stimme der ",
        "I agree to the ",
        "Consent text before privacy link",
        True,
    ),
    (
        "contact.form.consent_zu",
        "contact",
        " zu.",
        ".",
        "Consent text after privacy link (DE 'zu.', EN period)",
        True,
    ),
    (
        "contact.form.success.heading",
        "contact",
        "Vielen Dank!",
        "Thank you!",
        "Contact form: success panel heading",
        False,
    ),
    # Map section
    (
        "contact.map.eyebrow",
        "contact",
        "Standort",
        "Location",
        "Map section eyebrow",
        False,
    ),
    (
        "contact.map.heading",
        "contact",
        "So finden Sie uns",
        "Find us",
        "Map section heading",
        False,
    ),
    (
        "contact.map.open_external",
        "contact",
        "In Karten öffnen",
        "Open in maps",
        "Map external-link button",
        False,
    ),
    (
        "contact.map.empty.title",
        "contact",
        "Karte nicht verfügbar",
        "Map not available",
        "Map empty-state title",
        False,
    ),
    (
        "contact.map.empty.body",
        "contact",
        "Die Standortkoordinaten wurden noch nicht hinterlegt.",
        "Location coordinates have not been added yet.",
        "Map empty-state body",
        False,
    ),
    # ════════════════════════════════════════════════════════════════════
    # FAQ PAGE (/faq, /en/faq)
    # ════════════════════════════════════════════════════════════════════
    (
        "faq.page.eyebrow",
        "faq",
        "FAQ",
        "FAQ",
        "FAQ page hero eyebrow",
        False,
    ),
    (
        "faq.page.title",
        "faq",
        "Häufige Fragen",
        "Frequently asked questions",
        "FAQ page H1, breadcrumb and meta title",
        False,
    ),
    (
        "faq.page.subhead",
        "faq",
        "Antworten rund um Buchung, Preise und unsere Leistungen auf einen Blick.",
        "Answers about booking, prices and our services at a glance.",
        "FAQ page hero lead and meta description",
        False,
    ),
    (
        "faq.page.empty",
        "faq",
        "Die Antworten werden in Kürze ergänzt. Bis dahin helfen wir Ihnen gern persönlich weiter.",
        "Answers will be added shortly. Until then, we are happy to help you in person.",
        "FAQ page: shown when no FAQ is published",
        False,
    ),
    (
        "faq.category.general",
        "faq",
        "Allgemein",
        "General",
        "FAQ group heading: category general",
        False,
    ),
    (
        "faq.category.booking",
        "faq",
        "Buchung & Ablauf",
        "Booking & process",
        "FAQ group heading: category booking",
        False,
    ),
    (
        "faq.category.pricing",
        "faq",
        "Preise & Bezahlung",
        "Prices & payment",
        "FAQ group heading: category pricing",
        False,
    ),
    (
        "faq.category.other",
        "faq",
        "Weitere Fragen",
        "Further questions",
        "FAQ group heading: any category without its own label",
        False,
    ),
    (
        "faq.cta.heading",
        "faq",
        "Ihre Frage ist nicht dabei?",
        "Didn't find your question?",
        "FAQ page closing card heading",
        False,
    ),
    (
        "faq.cta.body",
        "faq",
        "Rufen Sie uns an oder schreiben Sie uns — wir helfen Ihnen gern persönlich weiter.",
        "Give us a call or send us a message — we are happy to help in person.",
        "FAQ page closing card body",
        False,
    ),
    (
        "faq.cta.contact",
        "faq",
        "Kontakt aufnehmen",
        "Get in touch",
        "FAQ page closing card button",
        False,
    ),
    # ════════════════════════════════════════════════════════════════════
    # BOOKING WIZARD — full step-by-step coverage
    # ════════════════════════════════════════════════════════════════════
    # Page shell
    (
        "booking.page.title",
        "booking",
        "Fahrt buchen",
        "Book your ride",
        "Booking page H1",
        True,
    ),
    (
        "booking.page.subhead",
        "booking",
        "In wenigen Schritten zur unverbindlichen Buchungsanfrage. Wir melden uns mit Ihrem Preis — online vorbestellt sparen Sie bis zu 5 %.",
        "A few steps to your non-binding booking request. We'll get back with your price — book online and save up to 5%.",
        "Booking page subhead",
        True,
    ),
    (
        "booking.page.eyebrow",
        "booking",
        "Anfrage",
        "Inquiry",
        "Booking page eyebrow above H1",
        False,
    ),
    # Wizard frame (heading row + sidebar next to the steps)
    (
        "booking.wizard.heading",
        "booking",
        "Buchungsdetails",
        "Booking details",
        "Wizard card heading",
        False,
    ),
    (
        "booking.wizard.summary",
        "booking",
        "In wenigen Schritten zur klaren Anfrage. Wir bestätigen anschließend persönlich.",
        "A clear booking request in a few steps. We follow up personally after submission.",
        "Wizard card lead, right of the heading",
        False,
    ),
    (
        "booking.sidebar.eyebrow",
        "booking",
        "Warum StepNow",
        "Why StepNow",
        "Wizard sidebar eyebrow",
        False,
    ),
    (
        "booking.sidebar.heading",
        "booking",
        "Klare Anfrage statt offener Fahrt",
        "A clear request instead of an uncertain ride",
        "Wizard sidebar heading",
        False,
    ),
    (
        "booking.sidebar.point_1",
        "booking",
        "Transparenter Preis und persönliche Rückmeldung statt unklarer Verfügbarkeit.",
        "Transparent price and a personal reply instead of uncertain availability.",
        "Wizard sidebar bullet 1",
        False,
    ),
    (
        "booking.sidebar.point_2",
        "booking",
        "Vorbestellung für Flughafen-Transfer, Arzt- & Klinikfahrten und private Strecken.",
        "Advance booking for airport transfers, doctor and clinic rides, and private routes.",
        "Wizard sidebar bullet 2",
        False,
    ),
    (
        "booking.sidebar.point_3",
        "booking",
        "Direkter Kontakt, falls Details vor der Fahrt abgestimmt werden müssen.",
        "Direct contact if details need to be clarified before the ride.",
        "Wizard sidebar bullet 3",
        False,
    ),
    # Progress / step labels
    (
        "booking.progress.step_of",
        "booking",
        "Schritt {current} von {total}",
        "Step {current} of {total}",
        "Progress indicator (uses {current} and {total} placeholders)",
        True,
    ),
    ("booking.step.service", "booking", "Leistung", "Service", "Step 1 label", True),
    ("booking.step.route", "booking", "Strecke", "Route", "Step 2 label", True),
    ("booking.step.details", "booking", "Details", "Details", "Step 3 label", True),
    ("booking.step.contact", "booking", "Kontakt", "Contact", "Step 4 label", True),
    ("booking.step.review", "booking", "Bestätigen", "Review", "Step 5 label", True),
    # Step 1 — service
    (
        "booking.service.heading",
        "booking",
        "Welche Leistung benötigen Sie?",
        "Which service do you need?",
        "Step 1 heading",
        True,
    ),
    (
        "booking.service.subhead",
        "booking",
        "Wählen Sie die Art Ihrer Fahrt und den gewünschten Termin.",
        "Choose the type of ride and your preferred time.",
        "Step 1 subhead",
        True,
    ),
    (
        "booking.service.date_label",
        "booking",
        "Datum",
        "Date",
        "Step 1 date input label",
        True,
    ),
    (
        "booking.service.time_label",
        "booking",
        "Uhrzeit",
        "Time",
        "Step 1 time input label",
        True,
    ),
    (
        "booking.service.select",
        "booking",
        "Auswählen",
        "Select",
        "Step 1: badge on an unselected service card",
        False,
    ),
    (
        "booking.service.selected",
        "booking",
        "Ausgewählt",
        "Selected",
        "Step 1: badge on the selected service card",
        False,
    ),
    # Step 2 — route
    (
        "booking.route.heading",
        "booking",
        "Wo soll die Fahrt beginnen und enden?",
        "Where does the ride start and end?",
        "Step 2 heading",
        True,
    ),
    (
        "booking.route.subhead",
        "booking",
        "Vollständige Adressen helfen uns, den besten Preis zu berechnen.",
        "Complete addresses help us calculate the best price.",
        "Step 2 subhead",
        True,
    ),
    (
        "booking.route.pickup_label",
        "booking",
        "Abholung",
        "Pickup",
        "Step 2 pickup fieldset legend",
        True,
    ),
    (
        "booking.route.destination_label",
        "booking",
        "Ziel",
        "Destination",
        "Step 2 destination fieldset legend",
        True,
    ),
    (
        "booking.route.address_label",
        "booking",
        "Adresse",
        "Address",
        "Step 2 address field label",
        True,
    ),
    (
        "booking.route.postcode_label",
        "booking",
        "PLZ",
        "Postal code",
        "Step 2 postcode field label",
        True,
    ),
    (
        "booking.route.city_label",
        "booking",
        "Ort",
        "City",
        "Step 2 city field label",
        True,
    ),
    # Step 3 — details
    (
        "booking.details.heading",
        "booking",
        "Passagiere & Gepäck",
        "Passengers & luggage",
        "Step 3 heading",
        True,
    ),
    (
        "booking.details.subhead",
        "booking",
        "Pro Fahrzeug fahren bis zu 4 Personen — für größere Gruppen setzen wir mehrere Fahrzeuge ein. Sonderwünsche bitte unten angeben.",
        "Each vehicle carries up to 4 persons — for larger groups we deploy several vehicles. Note any special requirements below.",
        "Step 3 subhead",
        True,
    ),
    (
        "booking.details.passengers_label",
        "booking",
        "Fahrgäste",
        "Passengers",
        "Step 3 passengers counter label",
        True,
    ),
    (
        "booking.details.luggage_label",
        "booking",
        "Gepäckstücke",
        "Luggage pieces",
        "Step 3 luggage counter label",
        True,
    ),
    (
        "booking.details.notes_label",
        "booking",
        "Besondere Hinweise (optional)",
        "Special requirements (optional)",
        "Step 3 textarea label",
        True,
    ),
    # Step 4 — contact
    (
        "booking.contact.heading",
        "booking",
        "Ihre Kontaktdaten",
        "Your contact details",
        "Step 4 heading",
        True,
    ),
    (
        "booking.contact.subhead",
        "booking",
        "Damit wir uns mit Ihrem Preis melden können.",
        "So we can get back to you with your price.",
        "Step 4 subhead",
        True,
    ),
    (
        "booking.contact.name_label",
        "booking",
        "Name",
        "Name",
        "Step 4 name field label",
        True,
    ),
    (
        "booking.contact.phone_label",
        "booking",
        "Telefon",
        "Phone",
        "Step 4 phone field label",
        True,
    ),
    (
        "booking.contact.email_label",
        "booking",
        "E-Mail",
        "Email",
        "Step 4 email field label",
        True,
    ),
    (
        "booking.contact.business_toggle",
        "booking",
        "Ich buche als Geschäftskunde",
        "I'm booking as a business customer",
        "Step 4 business toggle label",
        True,
    ),
    (
        "booking.contact.company_label",
        "booking",
        "Firmenname",
        "Company name",
        "Step 4 company name field label",
        True,
    ),
    (
        "booking.contact.vat_label",
        "booking",
        "USt-IdNr.",
        "VAT ID",
        "Step 4 VAT ID field label",
        True,
    ),
    # Step 5 — review
    (
        "booking.review.heading",
        "booking",
        "Bitte prüfen und bestätigen",
        "Please review and confirm",
        "Step 5 heading",
        True,
    ),
    (
        "booking.review.subhead",
        "booking",
        "Buchungsanfrage absenden — wir melden uns innerhalb von 30 Minuten mit Ihrem Preis.",
        "Submit your booking request — we'll come back with your price within 30 minutes.",
        "Step 5 subhead",
        True,
    ),
    (
        "booking.review.service",
        "booking",
        "Leistung",
        "Service",
        "Step 5 review row: service",
        True,
    ),
    ("booking.review.when", "booking", "Wann", "When", "Step 5 review row: when", True),
    (
        "booking.review.consent_intro",
        "booking",
        "Ich stimme der ",
        "I agree to the ",
        "Step 5 consent text before privacy link",
        True,
    ),
    (
        "booking.review.consent_zu",
        "booking",
        " zu.",
        ".",
        "Step 5 consent text after privacy link",
        True,
    ),
    (
        "booking.review.submit",
        "booking",
        "Buchungsanfrage absenden",
        "Submit booking request",
        "Step 5 submit button",
        True,
    ),
    # Help line below wizard
    (
        "booking.help.heading",
        "booking",
        "Brauchen Sie Hilfe bei der Buchung?",
        "Need help with your booking?",
        "Help line above phone number",
        False,
    ),
    (
        "booking.help.eyebrow",
        "booking",
        "Direkte Hilfe",
        "Direct help",
        "Help card eyebrow below the wizard",
        False,
    ),
    (
        "booking.help.body",
        "booking",
        "Wenn die Fahrt kurzfristig ist oder besondere Anforderungen hat, rufen Sie uns direkt an.",
        "If the ride is at short notice or has special requirements, call us directly.",
        "Help card body below the wizard",
        False,
    ),
    # Confirmation page
    (
        "booking.confirmation.heading",
        "booking",
        "Buchungsanfrage gesendet",
        "Booking request received",
        "Confirmation page heading",
        True,
    ),
    (
        "booking.confirmation.body",
        "booking",
        "Wir melden uns innerhalb von 30 Minuten mit einem verbindlichen Angebot.",
        "We'll get back to you within 30 minutes with a binding quote.",
        "Confirmation body",
        True,
    ),
    (
        "booking.confirmation.reference_label",
        "booking",
        "Ihre Referenznummer",
        "Your reference number",
        "Confirmation reference label",
        True,
    ),
    (
        "booking.confirmation.next_steps_heading",
        "booking",
        "Wie es weitergeht",
        "What happens next",
        "Confirmation next-steps heading",
        True,
    ),
    (
        "booking.confirmation.next_step_1",
        "booking",
        "Sie erhalten innerhalb von 30 Minuten zu unseren Telefonzeiten eine Rückmeldung mit Ihrem Preis.",
        "Within 30 minutes during our phone hours, we'll get back to you with your price.",
        "Confirmation step 1",
        True,
    ),
    (
        "booking.confirmation.next_step_2",
        "booking",
        "Nach Ihrer Bestätigung wird die Fahrt fest gebucht.",
        "Once you confirm, the ride is firmly booked.",
        "Confirmation step 2",
        True,
    ),
    (
        "booking.confirmation.next_step_3",
        "booking",
        "Am Tag der Fahrt erhalten Sie eine SMS mit Fahrer- und Fahrzeuginformationen.",
        "On the day of the ride, you'll receive an SMS with driver and vehicle details.",
        "Confirmation step 3",
        True,
    ),
    (
        "booking.confirmation.urgent_heading",
        "booking",
        "Dringend?",
        "Urgent?",
        "Confirmation urgent block heading",
        True,
    ),
    (
        "booking.confirmation.urgent_body",
        "booking",
        "Für kurzfristige Buchungen rufen Sie uns direkt an.",
        "For short-notice bookings, please call us directly.",
        "Confirmation urgent block body",
        True,
    ),
    (
        "booking.confirmation.cta_home",
        "booking",
        "Zur Startseite",
        "Back to homepage",
        "Confirmation home CTA",
        True,
    ),
    (
        "booking.confirmation.sidebar.eyebrow",
        "booking",
        "Ihre Anfrage",
        "Your request",
        "Confirmation sidebar card eyebrow",
        False,
    ),
    (
        "booking.confirmation.sidebar.heading",
        "booking",
        "Persönlich bestätigt, nicht automatisch abgefertigt",
        "Personally confirmed, not auto-processed",
        "Confirmation sidebar card heading",
        False,
    ),
    (
        "booking.confirmation.sidebar.body",
        "booking",
        "Ihre Anfrage wird manuell geprüft. So können wir Route, Verfügbarkeit und besondere Hinweise sauber bestätigen.",
        "Your request is checked manually so we can confirm route, availability and any special requirements properly.",
        "Confirmation sidebar card body",
        False,
    ),
    (
        "booking.confirmation.contact.eyebrow",
        "booking",
        "Direkter Kontakt",
        "Direct contact",
        "Confirmation contact card eyebrow",
        False,
    ),
    (
        "booking.confirmation.contact.heading",
        "booking",
        "Rückfragen oder kurzfristige Fahrt?",
        "Questions or a short-notice ride?",
        "Confirmation contact card heading",
        False,
    ),
    (
        "booking.confirmation.contact.body",
        "booking",
        "Wenn sich etwas ändert oder die Fahrt dringend ist, erreichen Sie uns direkt per Telefon.",
        "If anything changes or the ride is urgent, you can reach us directly by phone.",
        "Confirmation contact card body",
        False,
    ),
    # ════════════════════════════════════════════════════════════════════
    # CONSENT BANNER (DSGVO)
    # ════════════════════════════════════════════════════════════════════
    (
        "consent.eyebrow",
        "consent",
        "Datenschutz",
        "Privacy",
        "Banner eyebrow",
        False,
    ),
    (
        "consent.body",
        "consent",
        "Wir setzen nur technisch notwendige Cookies. Die Karte laden wir erst mit Ihrer Einwilligung von OpenStreetMap — dabei wird Ihre IP-Adresse übertragen.",
        "We only use strictly necessary cookies. The map is loaded from OpenStreetMap only with your consent — this transmits your IP address.",
        "Banner body paragraph",
        False,
    ),
    (
        "consent.privacy_link",
        "consent",
        "Datenschutzerklärung",
        "Privacy policy",
        "Banner inline privacy link",
        False,
    ),
    (
        "consent.reject_all",
        "consent",
        "Ablehnen",
        "Decline",
        "Banner: reject all button",
        False,
    ),
    (
        "consent.accept_all",
        "consent",
        "Karte erlauben",
        "Allow map",
        "Banner: accept all button",
        False,
    ),
    (
        "consent.footer_link",
        "consent",
        "Cookie-Einstellungen",
        "Cookie settings",
        "Footer re-open link",
        False,
    ),
    # ════════════════════════════════════════════════════════════════════
    # FOOTER
    # ════════════════════════════════════════════════════════════════════
    (
        "footer.col.brand",
        "footer",
        "StepNow Rides & Movers — Ihr zuverlässiger Partner für Personenbeförderung und Kurierdienste in Deizisau, Esslingen und Umgebung.",
        "StepNow Rides & Movers — your reliable partner for passenger transport and courier services in Deizisau, Esslingen and the surrounding area.",
        "Footer brand column tagline",
        False,
    ),
    (
        "footer.col.quick_links",
        "footer",
        "Schnellzugriff",
        "Quick links",
        "Footer column heading: quick links",
        False,
    ),
    (
        "footer.col.services",
        "footer",
        "Dienstleistungen",
        "Services",
        "Footer column heading: services",
        False,
    ),
    (
        "footer.col.contact",
        "footer",
        "Kontakt",
        "Contact",
        "Footer column heading: contact",
        False,
    ),
    (
        "footer.legal.impressum",
        "footer",
        "Impressum",
        "Legal notice",
        "Footer legal link: impressum",
        True,
    ),
    (
        "footer.legal.datenschutz",
        "footer",
        "Datenschutz",
        "Privacy",
        "Footer legal link: privacy",
        True,
    ),
    (
        "footer.legal.agb",
        "footer",
        "AGB",
        "Terms",
        "Footer legal link: AGB / terms",
        True,
    ),
    (
        "footer.rights_reserved",
        "footer",
        "Alle Rechte vorbehalten.",
        "All rights reserved.",
        "Suffix on bottom-strip copyright (year + business name rendered dynamically by Footer)",
        False,
    ),
    # ════════════════════════════════════════════════════════════════════
    # COMMON UI
    # ════════════════════════════════════════════════════════════════════
    ("common.call_us", "common", "Anrufen", "Call us", "Universal phone CTA", False),
    ("common.back", "common", "Zurück", "Back", "Generic back", True),
    (
        "common.continue",
        "common",
        "Weiter",
        "Continue",
        "Generic continue / next",
        True,
    ),
    ("common.edit", "common", "Ändern", "Edit", "Generic edit", True),
    # ════════════════════════════════════════════════════════════════════
    # ERRORS
    # ════════════════════════════════════════════════════════════════════
    (
        "errors.generic",
        "errors",
        "Ein Fehler ist aufgetreten. Bitte versuchen Sie es erneut.",
        "An error occurred. Please try again.",
        "Generic error",
        True,
    ),
    (
        "errors.page.eyebrow",
        "errors",
        "Fehler",
        "Error",
        "Error page eyebrow (route error boundary)",
        True,
    ),
    (
        "errors.page.heading",
        "errors",
        "Etwas ist schiefgelaufen",
        "Something went wrong",
        "Error page heading",
        True,
    ),
    (
        "errors.page.body",
        "errors",
        "Die Seite konnte nicht geladen werden. Bitte versuchen Sie es erneut.",
        "The page could not be loaded. Please try again.",
        "Error page body",
        True,
    ),
    (
        "errors.page.retry",
        "errors",
        "Erneut versuchen",
        "Try again",
        "Error page retry button",
        True,
    ),
    (
        "errors.required",
        "errors",
        "Dieses Feld ist erforderlich.",
        "This field is required.",
        "Required-field error",
        True,
    ),
    (
        "errors.email",
        "errors",
        "Bitte geben Sie eine gültige E-Mail-Adresse ein.",
        "Please enter a valid email address.",
        "Alias for errors.invalid_email used by ContactForm",
        True,
    ),
    (
        "errors.phone",
        "errors",
        "Bitte geben Sie eine gültige Telefonnummer ein.",
        "Please enter a valid phone number.",
        "Invalid phone",
        True,
    ),
    (
        "errors.lead_time",
        "errors",
        "Mindestens 60 Minuten Vorlauf erforderlich.",
        "At least 60 minutes lead time required.",
        "Booking lead-time error",
        True,
    ),
    (
        "errors.consent_required",
        "errors",
        "Bitte stimmen Sie der Datenschutzerklärung zu, um fortzufahren.",
        "Please accept the privacy policy to continue.",
        "DSGVO consent error",
        True,
    ),
    # ════════════════════════════════════════════════════════════════════
    # 404
    # ════════════════════════════════════════════════════════════════════
    (
        "404.heading",
        "errors",
        "Seite nicht gefunden",
        "Page not found",
        "404 heading",
        True,
    ),
    (
        "404.body",
        "errors",
        "Die gesuchte Seite existiert nicht oder wurde verschoben.",
        "The page you're looking for doesn't exist or has been moved.",
        "404 body",
        True,
    ),
    ("404.cta", "errors", "Zur Startseite", "Back to homepage", "404 CTA", True),
    # ════════════════════════════════════════════════════════════════════
    # LEGAL
    # ════════════════════════════════════════════════════════════════════
    (
        "legal.translation_disclaimer",
        "legal",
        "Dies ist eine Übersetzung zur Information. Rechtlich verbindlich ist die deutsche Fassung.",
        "This is a translation for your convenience. The German version is legally binding.",
        "EN legal page banner",
        True,
    ),
    (
        "legal.last_updated",
        "legal",
        "Stand",
        "Last updated",
        "Legal page date label",
        False,
    ),
    (
        "booking.confirmation.eyebrow",
        "booking",
        "Anfrage erhalten",
        "Request received",
        "Confirmation page eyebrow above headline",
        False,
    ),
    (
        "common.copy",
        "common",
        "Kopieren",
        "Copy",
        "Generic copy-to-clipboard action",
        False,
    ),
    (
        "common.copied",
        "common",
        "Kopiert",
        "Copied",
        "Generic copy success state",
        False,
    ),
    # ════════════════════════════════════════════════════════════════════
    # MISSING KEYS — backfill (from i18n runtime warnings)
    # ════════════════════════════════════════════════════════════════════
    # Homepage — How it works (section lead)
    (
        "home.how.summary",
        "home",
        "In drei einfachen Schritten zu Ihrer Fahrt — anfragen, bestätigen lassen, einsteigen.",
        "Three simple steps to your ride — request, get confirmation, get going.",
        "How-it-works section lead paragraph",
        False,
    ),
    # Homepage — Testimonials (section lead)
    (
        "home.testimonials.lead",
        "home",
        "Echte Stimmen von Fahrgästen aus Plochingen, Esslingen und dem mittleren Neckartal.",
        "Real voices from passengers in Plochingen, Esslingen and the central Neckar valley.",
        "Testimonials section lead paragraph",
        False,
    ),
    # Services — How it works (section lead/summary)
    (
        "services.hiw.summary",
        "services",
        "Vom ersten Kontakt bis zur Ankunft — transparent und ohne versteckte Kosten.",
        "From first contact to arrival — transparent and without hidden costs.",
        "Services HIW section lead paragraph",
        False,
    ),
    # Contact — Form column lead
    (
        "contact.form.lead",
        "contact",
        "Schreiben Sie uns Ihr Anliegen. Wir melden uns mit einer klaren Rückmeldung während unserer Servicezeiten.",
        "Send us your request. We respond with a clear follow-up during our service hours.",
        "Contact form column lead (right-aligned beside heading)",
        False,
    ),
    # Contact — Methods column lead
    (
        "contact.methods.lead",
        "contact",
        "Telefon, E-Mail und Standort auf einen Blick. Für kurze Rückfragen ist der direkte Kontakt meist der schnellste Weg.",
        "Phone, email, and location in one place. For short questions, direct contact is usually the fastest route.",
        "Contact methods column lead",
        False,
    ),
    # Contact — FAQ block
    (
        "contact.faq.eyebrow",
        "contact",
        "FAQ",
        "FAQ",
        "Contact FAQ eyebrow (small caps)",
        False,
    ),
    (
        "contact.faq.lead",
        "contact",
        "Antworten auf die häufigsten Fragen rund um Buchung, Preise und Ablauf.",
        "Answers to the most common questions about booking, pricing and how it works.",
        "Contact FAQ lead paragraph",
        False,
    ),
    (
        "contact.faq.jump",
        "contact",
        "Alle Fragen ansehen",
        "View all questions",
        "Contact FAQ jump/CTA link",
        False,
    ),
    # Pricing — per-service tab taglines (rendered over hero band)
    (
        "pricing.tab.airport-transfer.tagline",
        "pricing",
        "Festpreise ab Ihrem Wohnort.",
        "Fixed prices from your home town.",
        "Pricing tab tagline: airport transfer",
        False,
    ),
    (
        "pricing.tab.hospital-transport.tagline",
        "pricing",
        "Sicher und geduldig zu jedem Termin.",
        "Safe and patient to every appointment.",
        "Pricing tab tagline: hospital transport",
        False,
    ),
    (
        "pricing.tab.shuttle-service.tagline",
        "pricing",
        "Transparent nach Tarif — bis zu 4 Personen.",
        "Transparent tariff — up to 4 persons.",
        "Pricing tab tagline: shuttle service",
        False,
    ),
    (
        "pricing.tab.courier-transport.tagline",
        "pricing",
        "Express · Terminfracht · Firmendienst.",
        "Express · scheduled freight · business service.",
        "Pricing tab tagline: courier transport",
        False,
    ),
    # German-slug duplicates (DE pricing page keys tabs by the German slug)
    (
        "pricing.tab.flughafentransfer.tagline",
        "pricing",
        "Festpreise ab Ihrem Wohnort.",
        "Fixed prices from your home town.",
        "Pricing tab tagline: airport transfer (DE slug)",
        False,
    ),
    (
        "pricing.tab.krankenhausfahrten.tagline",
        "pricing",
        "Sicher und geduldig zu jedem Termin.",
        "Safe and patient to every appointment.",
        "Pricing tab tagline: hospital transport (DE slug)",
        False,
    ),
    (
        "pricing.tab.kurier-sondertransport.tagline",
        "pricing",
        "Express · Terminfracht · Firmendienst.",
        "Express · scheduled freight · business service.",
        "Pricing tab tagline: courier transport (DE slug)",
        False,
    ),
    # Pricing — empty state body
    (
        "pricing.empty.body",
        "pricing",
        "Für diese Leistung erstellen wir Ihnen gern ein individuelles Angebot — innerhalb von 30 Minuten zu unseren Telefonzeiten.",
        "We are happy to prepare an individual quote for this service — within 30 minutes during our phone hours.",
        "Empty pricing state body",
        False,
    ),
    # Pricing page — price list units, discounts, notes (flyer + Preisliste)
    (
        "services.row.kurier-sondertransport.diff_label",
        "services",
        "PKW/Kombi oder Sprinter",
        "Car/estate or Sprinter",
        "services.row.kurier-sondertransport.diff_label (flyer alignment)",
        False,
    ),
    (
        "services.row.kurier-sondertransport.diff_body",
        "services",
        "— Grundpreis inkl. 5 km und 1 Std. Be-/Entladezeit, Express-Zuschlag bei Bedarf.",
        "— base price incl. 5 km and 1 hour of loading, express surcharge when needed.",
        "services.row.kurier-sondertransport.diff_body (flyer alignment)",
        False,
    ),
    (
        "services.row.courier-transport.diff_label",
        "services",
        "PKW/Kombi oder Sprinter",
        "Car/estate or Sprinter",
        "services.row.courier-transport.diff_label (flyer alignment)",
        False,
    ),
    (
        "services.row.courier-transport.diff_body",
        "services",
        "— Grundpreis inkl. 5 km und 1 Std. Be-/Entladezeit, Express-Zuschlag bei Bedarf.",
        "— base price incl. 5 km and 1 hour of loading, express surcharge when needed.",
        "services.row.courier-transport.diff_body (flyer alignment)",
        False,
    ),
    (
        "pricing.table.item",
        "pricing",
        "Leistung / Strecke",
        "Service / route",
        "pricing.table.item (flyer alignment)",
        False,
    ),
    (
        "pricing.unit.km",
        "pricing",
        "/ km",
        "/ km",
        "pricing.unit.km (flyer alignment)",
        False,
    ),
    (
        "pricing.unit.min",
        "pricing",
        "/ Min.",
        "/ min",
        "pricing.unit.min (flyer alignment)",
        False,
    ),
    (
        "pricing.price.from",
        "pricing",
        "ab",
        "from",
        "pricing.price.from (flyer alignment)",
        False,
    ),
    (
        "pricing.price.on_request",
        "pricing",
        "Auf Anfrage",
        "On request",
        "pricing.price.on_request (flyer alignment)",
        False,
    ),
    (
        "pricing.price.net",
        "pricing",
        "netto",
        "net",
        "pricing.price.net (flyer alignment)",
        False,
    ),
    (
        "pricing.included.vat.label",
        "pricing",
        "Gesetzliche MwSt.",
        "Statutory VAT",
        "pricing.included.vat.label (flyer alignment)",
        False,
    ),
    (
        "pricing.included.vat.desc",
        "pricing",
        "— bei allen Personenfahrten bereits enthalten.",
        "— already included in every passenger fare.",
        "pricing.included.vat.desc (flyer alignment)",
        False,
    ),
    (
        "pricing.excluded.waiting",
        "pricing",
        "Wartezeit nach Tarif (pro Minute)",
        "Waiting time at tariff (per minute)",
        "pricing.excluded.waiting (flyer alignment)",
        False,
    ),
    (
        "pricing.cancellation.body",
        "pricing",
        "Planänderung? Sagen Sie Ihre Fahrt bitte so früh wie möglich ab — telefonisch, per WhatsApp oder E-Mail. Es gelten unsere Allgemeinen Geschäftsbedingungen.",
        "Change of plans? Please cancel your ride as early as possible — by phone, WhatsApp or email. Our general terms and conditions apply.",
        "pricing.cancellation.body (flyer alignment)",
        False,
    ),
    (
        "pricing.discounts.eyebrow",
        "pricing",
        "Rabatte & Hinweise",
        "Discounts & notes",
        "pricing.discounts.eyebrow (flyer alignment)",
        False,
    ),
    (
        "pricing.discounts.heading",
        "pricing",
        "Vorbestellen lohnt sich.",
        "Booking ahead pays off.",
        "pricing.discounts.heading (flyer alignment)",
        False,
    ),
    (
        "pricing.discounts.online.label",
        "pricing",
        "Bis zu 5 % Rabatt",
        "Up to 5% off",
        "pricing.discounts.online.label (flyer alignment)",
        False,
    ),
    (
        "pricing.discounts.online.desc",
        "pricing",
        "— wenn Sie online über step-now.de/buchen vorbestellen.",
        "— when you pre-book online at step-now.de/buchen.",
        "pricing.discounts.online.desc (flyer alignment)",
        False,
    ),
    (
        "pricing.discounts.return.label",
        "pricing",
        "10 % Rabatt auf die Rückfahrt",
        "10% off the return trip",
        "pricing.discounts.return.label (flyer alignment)",
        False,
    ),
    (
        "pricing.discounts.return.desc",
        "pricing",
        "— wenn Sie innerhalb einer Stunde mit uns zurückfahren.",
        "— when you ride back with us within one hour.",
        "pricing.discounts.return.desc (flyer alignment)",
        False,
    ),
    (
        "pricing.discounts.oneway.label",
        "pricing",
        "Je einfache Fahrt",
        "Per one-way trip",
        "pricing.discounts.oneway.label (flyer alignment)",
        False,
    ),
    (
        "pricing.discounts.oneway.desc",
        "pricing",
        "— Hin- und Rückfahrt sind zwei getrennte Fahrten.",
        "— outbound and return are two separate trips.",
        "pricing.discounts.oneway.desc (flyer alignment)",
        False,
    ),
    (
        "pricing.discounts.capacity.label",
        "pricing",
        "Bis zu 4 Personen",
        "Up to 4 persons",
        "pricing.discounts.capacity.label (flyer alignment)",
        False,
    ),
    (
        "pricing.discounts.capacity.desc",
        "pricing",
        "— Fahrzeugkapazität; eine eigene Preisstufe für mehr Personen gibt es nicht.",
        "— vehicle capacity; there is no separate price tier for more persons.",
        "pricing.discounts.capacity.desc (flyer alignment)",
        False,
    ),
    # SEO — dedicated meta descriptions (≤ 160 chars) for pages whose visible subhead is not one
    (
        "home.meta_description",
        "home",
        "StepNow Rides & Movers: vorbestellte Fahrten und Kurierdienste in Deizisau, Plochingen und Esslingen. Festpreise zum Flughafen und Hauptbahnhof Stuttgart.",
        "StepNow Rides & Movers: pre-booked rides and courier services in Deizisau, Plochingen and Esslingen. Fixed prices to Stuttgart Airport and Central Station.",
        "Meta description (home page)",
        False,
    ),
    (
        "contact.meta_description",
        "contact",
        "Kontakt zu StepNow per Telefon, WhatsApp oder E-Mail. Fahrten und Kurierdienste in Deizisau, Plochingen und Esslingen vorbestellen — Antwort in 30 Minuten.",
        "Contact StepNow by phone, WhatsApp or email. Pre-book rides and courier services in Deizisau, Plochingen and Esslingen — reply within 30 minutes.",
        "Meta description (contact page)",
        False,
    ),
    (
        "about.meta_description",
        "about",
        "StepNow Rides & Movers, Naeem Ahmad e.K. aus Deizisau: Mietwagen mit Fahrer nach § 49 PBefG und Kurierdienste — persönlich, pünktlich, transparent.",
        "StepNow Rides & Movers, Naeem Ahmad e.K. from Deizisau: private-hire rides under § 49 PBefG and courier services — personal, punctual, transparent.",
        "Meta description (about page)",
        False,
    ),
    (
        "faq.meta_description",
        "faq",
        "Antworten zu Buchung, Preisen, Flughafen-Transfer, Arzt- und Klinikfahrten und Kurierdiensten von StepNow in Deizisau, Plochingen und Esslingen.",
        "Answers about booking, prices, airport transfers, doctor and clinic rides and courier services from StepNow in Deizisau, Plochingen and Esslingen.",
        "Meta description (faq page)",
        False,
    ),
]


FIELDS = ("namespace", "value_de", "value_en", "description", "is_locked")


def _snapshot(row: UiString) -> dict:
    return {"key": row.key, **{f: getattr(row, f) for f in FIELDS}}


def run() -> None:
    log_section(f"UI strings ({len(UI_STRINGS)} keys)")
    db = SessionLocal()
    try:
        actor = get_system_actor(db)
        human_ids = human_edited_ids(db, "ui_strings")
        # Live row wins over a soft-deleted one with the same key (ordered deleted-first, live last).
        rows = {r.key: r for r in db.query(UiString).order_by(UiString.is_deleted.desc()).all()}
        counts = {"created": 0, "updated": 0, "unchanged": 0, "kept": 0, "pruned": 0}
        for key, namespace, value_de, value_en, description, is_locked in UI_STRINGS:
            values = {"namespace": namespace, "value_de": value_de, "value_en": value_en, "description": description, "is_locked": is_locked}
            row = rows.get(key)
            if row is None:
                row = UiString(key=key, **values, seed_hash=seed_fingerprint(values))
                db.add(row)
                db.flush()
                AuditService.log(db, actor, "ui_strings", str(row.id), "create", None, _snapshot(row), None)
                counts["created"] += 1
                continue
            action = reconcile(row, values, human_ids, actor)
            if action == "kept":
                log_kept(key)
                counts["kept"] += 1
                continue
            if action == "same":
                row.seed_hash = seed_fingerprint(values)
                counts["unchanged"] += 1
                continue
            before = _snapshot(row)
            for field, value in values.items():
                setattr(row, field, value)
            row.is_deleted, row.deleted_at, row.deleted_by = False, None, None
            row.seed_hash = seed_fingerprint(values)
            db.flush()
            AuditService.log(db, actor, "ui_strings", str(row.id), "update", before, _snapshot(row), None)
            counts["updated"] += 1
        seeded_keys = {entry[0] for entry in UI_STRINGS}
        for key, row in rows.items():
            if key in seeded_keys or row.is_deleted:
                continue
            if not is_unedited(row, FIELDS, human_ids):
                log_action(key, "kept", "no longer seeded, but customized or created in admin")
                continue
            row.is_deleted, row.deleted_at, row.deleted_by = True, datetime.now(timezone.utc), actor.id
            AuditService.log(db, actor, "ui_strings", str(row.id), "soft_delete", _snapshot(row), None, None, notes="removed from seed_ui_strings")
            counts["pruned"] += 1
        db.commit()
        print("  [done] " + ", ".join(f"{n} {label}" for label, n in counts.items()))
    finally:
        db.close()


if __name__ == "__main__":
    run()
