// apps/frontend/src/services/api/endpoints.ts
// Backend path constants. Adds DASHBOARD_TOTALS, BOOKINGS_HEATMAP, BOOKINGS_UPCOMING for the new aggregation endpoints used by the dashboard SSR pass (M-3).

export const ENDPOINTS = {
PUBLIC: {
HEALTH: "/public/health",
SETTINGS: "/public/settings",
UI_STRINGS: "/public/ui-strings",
SERVICES: "/public/services",
SERVICE_BY_SLUG: (slug: string) => `/public/services/${encodeURIComponent(slug)}`,
SERVICE_PRICING: (slug: string) => `/public/services/${encodeURIComponent(slug)}/pricing`,
PRICING_ALL: "/public/pricing",
VEHICLES: "/public/vehicles",
FAQS: "/public/faqs",
TESTIMONIALS: "/public/testimonials",
LEGAL_PAGE: (slug: string) => `/public/legal-pages/${encodeURIComponent(slug)}`,
BOOKINGS: "/public/bookings",
CONTACT: "/public/contact",
},
AUTH: {
LOGIN: "/auth/login",
REFRESH: "/auth/refresh",
LOGOUT: "/auth/logout",
ME: "/auth/me",
},
ADMIN: {
SETTINGS: "/admin/settings",
UI_STRINGS: "/admin/ui-strings",
UI_STRING_BY_ID: (id: string) => `/admin/ui-strings/${id}`,
UI_STRING_RESTORE: (id: string) => `/admin/ui-strings/${id}/restore`,
SERVICES: "/admin/services",
SERVICE_BY_ID: (id: string) => `/admin/services/${id}`,
SERVICE_RESTORE: (id: string) => `/admin/services/${id}/restore`,
VEHICLES: "/admin/vehicles",
VEHICLE_BY_ID: (id: string) => `/admin/vehicles/${id}`,
VEHICLE_RESTORE: (id: string) => `/admin/vehicles/${id}/restore`,
FAQS: "/admin/faqs",
FAQ_BY_ID: (id: string) => `/admin/faqs/${id}`,
FAQ_RESTORE: (id: string) => `/admin/faqs/${id}/restore`,
TESTIMONIALS: "/admin/testimonials",
TESTIMONIAL_BY_ID: (id: string) => `/admin/testimonials/${id}`,
TESTIMONIAL_RESTORE: (id: string) => `/admin/testimonials/${id}/restore`,
SERVICE_PRICING_CATEGORIES: (serviceId: string) => `/admin/services/${serviceId}/pricing-categories`,
PRICING_CATEGORY: (id: string) => `/admin/pricing-categories/${id}`,
PRICING_CATEGORY_RESTORE: (id: string) => `/admin/pricing-categories/${id}/restore`,
PRICING_CATEGORY_ITEMS: (id: string) => `/admin/pricing-categories/${id}/items`,
PRICING_ITEM: (id: string) => `/admin/pricing-items/${id}`,
PRICING_ITEM_RESTORE: (id: string) => `/admin/pricing-items/${id}/restore`,
LEGAL_PAGES: "/admin/legal-pages",
LEGAL_PAGE: (slug: string) => `/admin/legal-pages/${slug}`,
LEGAL_PAGE_DRAFT: (slug: string) => `/admin/legal-pages/${slug}/draft`,
LEGAL_PAGE_PUBLISH: (slug: string) => `/admin/legal-pages/${slug}/publish`,
LEGAL_PAGE_ROLLBACK: (slug: string) => `/admin/legal-pages/${slug}/rollback`,
LEGAL_PAGE_VERSIONS: (slug: string) => `/admin/legal-pages/${slug}/versions`,
LEGAL_PAGE_PREVIEW: (slug: string) => `/admin/legal-pages/${slug}/preview`,
BOOKINGS: "/admin/bookings",
BOOKING_BY_ID: (id: string) => `/admin/bookings/${id}`,
BOOKINGS_REVENUE_SERIES: "/admin/bookings/revenue-series",
BOOKINGS_SERVICE_MIX: "/admin/bookings/service-mix",
BOOKINGS_HEATMAP: "/admin/bookings/heatmap",
BOOKINGS_UPCOMING: "/admin/bookings/upcoming",
CONTACT_MESSAGES: "/admin/contact-messages",
CONTACT_MESSAGE_BY_ID: (id: string) => `/admin/contact-messages/${id}`,
AUDIT_LOG: "/admin/audit-log",
AUDIT_LOG_BY_ID: (id: string) => `/admin/audit-log/${id}`,
DASHBOARD_TOTALS: "/admin/dashboard/totals",
},
} as const;
